### ISSUE TITLE
Javadoc warnings for generated classes

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#291] opened 2022-11-30 10:53 UTC
Javadoc don't like << or >> in comments and throws warnings. For writing Nalu version and generation time this chars will used:

https://github.com/NaluKit/nalu/blob/0f2ff85802926bbe30d54fe68a060ad5a82eb1ef/nalu-processor/src/main/java/com/github/nalukit/nalu/processor/util/BuildWithNaluCommentProvider.java#L23

Can create a PR if we have an idea for the replacement char.

**Comment by FrankHossfeld** [comment] 2022-11-30 11:59
A PR is highly appreciated ... 

I hink we just can remove '>>' and '<<'.

**Comment by mamta** [comment] 2022-12-01 08:33
The problem is due to the fact that - Javadoc plugin expects an opening and closing tag. Removing is one of the solutions.

**Comment by FrankHossfeld** [comment] 2022-12-01 09:46
In my opinion it is ok to use:

Build with Nalu version 2.11.0 at 022.11.30-12:00:00

or any other formatting instead of:

Build with Nalu version >>2.11.0<< at >>2022.11.30-12:00:00<<

It is just a comment. It is generated so you can check the client and processor are using the same version.

**Comment by TDesjardins** [comment] 2022-12-01 13:50
https://github.com/NaluKit/nalu/pull/292

**Comment by FrankHossfeld** [comment] 2022-12-01 14:33
PR is merged. I'll close the issue, cause it is fixed.
Thanks for contributing!

**Closed by FrankHossfeld** 2022-12-01 14:33 UTC
Labels: bug
