### ISSUE TITLE
Same RouteConfig added every time a Controller is modified

### ISSUE THREAD

**Issue by eguardiola** [NaluKit/nalu#104] opened 2019-10-29 14:37 UTC
This is an old issue that are affecting us since early versions of Nalu.

In our project, for example, every time a save is performed on ContractEditorContoller file (the same can be said for any Controller) then an additional RouteConfig is added on the generated XXXXApplicationImpl.java at the loadRoutes() method. So many duplicated RouteConfig can be added easily making the page presenting the same content repeated several times.

`java
	    super.routerConfiguration.getRouters().add(new RouteConfig("/fleetmanagement/database/contract/editor", Arrays.asList(new String[]{}), "page-wrapper", "es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"));
    sb01 = new StringBuilder();
    sb01.append("register route >>/fleetmanagement/database/contract/editor<< with parameter >><< for selector >>page-wrapper<< for controller >>es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController<<");
    ClientLogger.get().logDetailed(sb01.toString(), 3);`

This is something you are aware of ? We use Eclipse. Do you have any idea why this disturbing behaviour?

The only work around we have is to clean the project so all java code is compiled again.

**Comment by FrankHossfeld** [comment] 2019-10-29 16:22
Just to check, If I got it correct: 
You mean:

* edit a Controller and save

and then it has added a new RouteConfig?

**Comment by eguardiola** [comment] 2019-10-29 16:25
Yes, In Eclipse if you save a modified java file then it builds automatically the project so the java compiler is called and that way annotation processing too.

**Comment by FrankHossfeld** [comment] 2019-10-29 16:42
There is a explicit build triggered? Or just only a save and the JIT is running?

**Comment by eguardiola** [comment] 2019-10-29 16:49
Only a file save (Control + S) and the internal java compiler is triggered by Eclipse. This is the normal behaviour. But the annotation processor seems to be adding cloned entries for the same Controller on the loadroutes() method of the generated ApplicationImpl.java. I can comment out a line on the Controller, save the file and one more cloned  entry is added on ApplicationImpl.java.

**Comment by FrankHossfeld** [comment] 2019-10-29 16:57
Ok, got it! It is the just-in-time-compile. (JIT).

First, I am happy, that this works ... :-) cause I have implementet a special treatment to deal with this compile. The problem is, that when you save one file, the annotation processor only access this one file. 

Do deal with it Nalu wirtes a Meta file with all gather informations (you will find it inside the META-INF folder). Might be intresting to see, if the controller is reference more than once.

**Comment by eguardiola** [comment] 2019-10-29 17:47
Ok, i hope to have time to check out that tomorrow. Thanks Frank!

**Comment by eguardiola** [comment] 2019-10-30 07:34
Morning Frank,

I made several modifications to the ContractEditorController and i can see many cloned entries on the `target\classes\META-INF\nalu-route\nalu.properties` file as you can see below. ¿Can this be fixed?

````json
{ 
         "originalRoute":"/fleetmanagement/database/contract/editor",
         "route":"/fleetmanagement/database/contract/editor",
         "selector":"page-wrapper",
         "parameters":[ 

         ],
         "context":{ 
            "className":"es.foo.bar.mobile.client.ResponsiveApplicationContext"
         },
         "controller":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentInterface":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.IContractEditorComponent"
         },
         "component":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorComponent"
         },
         "provider":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentType":{ 
            "className":"elemental2.dom.HTMLElement"
         },
         "parameterAcceptors":[ 

         ],
         "composites":[ 

         ],
         "componentCreator":false
      },
      { 
         "originalRoute":"/fleetmanagement/database/contract/editor",
         "route":"/fleetmanagement/database/contract/editor",
         "selector":"page-wrapper",
         "parameters":[ 

         ],
         "context":{ 
            "className":"es.foo.bar.mobile.client.ResponsiveApplicationContext"
         },
         "controller":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentInterface":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.IContractEditorComponent"
         },
         "component":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorComponent"
         },
         "provider":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentType":{ 
            "className":"elemental2.dom.HTMLElement"
         },
         "parameterAcceptors":[ 

         ],
         "composites":[ 

         ],
         "componentCreator":false
      },
      { 
         "originalRoute":"/fleetmanagement/database/contract/editor",
         "route":"/fleetmanagement/database/contract/editor",
         "selector":"page-wrapper",
         "parameters":[ 

         ],
         "context":{ 
            "className":"es.foo.bar.mobile.client.ResponsiveApplicationContext"
         },
         "controller":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentInterface":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.IContractEditorComponent"
         },
         "component":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorComponent"
         },
         "provider":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentType":{ 
            "className":"elemental2.dom.HTMLElement"
         },
         "parameterAcceptors":[ 

         ],
         "composites":[ 

         ],
         "componentCreator":false
      },
      { 
         "originalRoute":"/fleetmanagement/database/contract/editor",
         "route":"/fleetmanagement/database/contract/editor",
         "selector":"page-wrapper",
         "parameters":[ 

         ],
         "context":{ 
            "className":"es.foo.bar.mobile.client.ResponsiveApplicationContext"
         },
         "controller":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentInterface":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.IContractEditorComponent"
         },
         "component":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorComponent"
         },
         "provider":{ 
            "className":"es.foo.bar.mobile.client.ui.fleetmanagement.database.contracts.editor.ContractEditorController"
         },
         "componentType":{ 
            "className":"elemental2.dom.HTMLElement"
         },
         "parameterAcceptors":[ 

         ],
         "composites":[ 

         ],
         "componentCreator":false
      }
````

**Comment by FrankHossfeld** [comment] 2019-10-30 09:21
I think, the problem is, that in case you have incremental builds (like in Eclipse) the RouteConfig is added without checking, if the config already exists. 

this does not matter in case you are doing a complete build, but seams to make problems in case we have an incremental build. 

Will look into it. Think, that can be fixed.

**Comment by eguardiola** [comment] 2019-10-30 09:33
Thanks Frank! That fix will free us of a long suffered pain!! xD

**Comment by FrankHossfeld** [comment] 2019-10-31 16:21
Done - please test with 1.3.5-SNAPSHOT. (SNAPSHOT is deployed to Maven Central.)

Please, let me know, if something does not work as expected. Otherwise close the issue.

**Closed by FrankHossfeld** 2019-10-31 16:21 UTC
Labels: bug

**Comment by eguardiola** [comment] 2019-10-31 20:11
Fixed!! Thanks!!! 😆
